version: '3.8'

services:
  bff:
    build:
      context: .
      target: ${NODE_ENV:-development}
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=8080
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
